FROM python:3.11.7-slim-bullseye

RUN groupadd -r python && useradd --no-log-init -r -g python python

RUN apt update && \
    apt install -y --no-install-recommends gcc libpq-dev build-essential cargo \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/include/locate.h /usr/include/xlocate.h

ENV PYTHONUNBUFFERED=1 APP_HOME=/ENRS/

RUN mkdir $APP_HOME
RUN chown -R python:python $APP_HOME

WORKDIR $APP_HOME
ADD . $APP_HOME
RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir /Microservices
RUN mkdir /Microservices/Data
COPY ./Microservices/Data/ /Microservices/Data/

RUN pip install gunicorn==21.2.0

EXPOSE 8050
USER python

CMD gunicorn -b 0.0.0.0:8050 main:server